### ISSUE TITLE
关于数据集

### ISSUE THREAD

**Issue by wuyancao** [XunpengYi/Text-IF#11]
谢谢您的回复，我还有个问题，EMS-lite这个数据集是基于MFNet，RoadScene 和LLVIP构造的，我想问问他们具体是怎么构造的，因为我没太看懂文章中实验部分中数据集使用的逻辑。

**Comment by XuedanWang** [comment]
同问

**Comment by XunpengYi** [comment]
数据集是为了解决现有多模态图像融合数据集中的源图像低质退化问题构造的。采用了人工修复、退化仿真、先进图像复原技术集合的方式构建的。具体来说，在训练时用低质量源图像作为输入，高质量源图像用于约束即可。
