### ISSUE TITLE
  关于MFnet数据

### ISSUE THREAD

**Issue by wahaha-debug** [XunpengYi/Text-IF#13]
作者您好，非常感谢您贡献的工作。
在复现的过程中，遇到一些问题
想请教您，您的noise数据集是怎么处理的？我下载的MFnet数据感觉像马赛克一样。
![00002D](https://github.com/user-attachments/assets/1fc48bda-4b0d-44fd-b7cd-a2460f100034)

**Comment by XunpengYi** [comment]
这个下载的图像是多通道重叠的，您可以用python读取后拆分成可见光和红外图像保存，这并不复杂。

**Comment by wahaha-debug** [comment]
> 这个下载的图像是多通道重叠的，您可以用python读取后拆分成可见光和红外图像保存，这并不复杂。

非常感谢您的解答，我去处理一下
