### ISSUE TITLE
what is the mean of gt

### ISSUE THREAD

**Issue by SiHaotia** [XunpengYi/Text-IF#14]
hello I do not know in datasets the vis_gt and ir_gt is what

**Comment by XunpengYi** [comment]
They are the high-quality, clean source images, different from the low-quality input images with degradation. Its representation of information is more accurate than that of the low-quality source images. We recommend using the high-quality images for supervision to achieve degradation removal in image fusion.

**Comment by SiHaotia** [comment]
may I ask you what method you have to get the high quality image， I would appreciate you if you can tell me， thank



发自我的iPad


------------------ Original ------------------
From: Xunpeng Yi ***@***.***&gt;
Date: Thu,Nov 14,2024 4:59 PM
To: XunpengYi/Text-IF ***@***.***&gt;
Cc: SiHaotia ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [XunpengYi/Text-IF] what is the mean of gt (Issue #14)





 
They are the high-quality, clean source images, different from the low-quality input images with degradation. Its representation of information is more accurate than that of the low-quality source images. We recommend using the high-quality images for supervision to achieve degradation removal in image fusion.

**Comment by XunpengYi** [comment]
For real degradations, we perform restoration by combining manual restoration with multiple advanced restoration algorithms, followed by manual selection. This approach was primarily used in the EMS-lite version. Furthermore, we have updated with more diverse degradations in https://github.com/XunpengYi/EMS. For other types of degradation, we simulate them by adding synthetic degradations. You can refer to the dataset creation webpage for more information.

**Comment by XunpengYi** [comment]
For real degradations, we perform the restoration by manual restoration or multiple advanced restoration algorithms followed by manual selection. This approach was primarily used in the EMS-lite version. Furthermore, we have updated with more diverse degradations in https://github.com/XunpengYi/EMS. For other types of degradation, we simulate them by adding synthetic degradations. You can refer to the EMS dataset creation webpage for more information.

**Comment by SiHaotia** [comment]
OK， thank you so much



发自我的iPhone


------------------ Original ------------------
From: Xunpeng Yi ***@***.***&gt;
Date: Thu,Nov 14,2024 5:09 PM
To: XunpengYi/Text-IF ***@***.***&gt;
Cc: SiHaotia ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [XunpengYi/Text-IF] what is the mean of gt (Issue #14)





 
For real degradations, we perform the restoration by manual restoration or multiple advanced restoration algorithms followed by manual selection. This approach was primarily used in the EMS-lite version. Furthermore, we have updated with more diverse degradations in https://github.com/XunpengYi/EMS. For other types of degradation, we simulate them by adding synthetic degradations. You can refer to the EMS dataset creation webpage for more information.
