### ISSUE TITLE
输出的融合图像大小与源图像大小不一致

### ISSUE THREAD

**Issue by liwead** [XunpengYi/Text-IF#15]
尊敬的作者你好，我对你的工作很感兴趣，尝试在MSRS,M3FD,RoadSence这三个数据集的测试集上使用你提供的预训练权重进行测试。我尝试计算融合结果图的EN,SD,SF,AG,SCD,VIF等多个指标，但是在M3FD,RoadSence这两个数据集的输出图像有部分生成的融合图像与源图像大小不一致，请问这是怎么回事儿

均使用该命令形式得到融合图像
#### RoadScene
CUDA_VISIBLE_DEVICES=0 python test_from_dataset.py  --weights_path "pretrained_weights/simple_fusion.pth" --dataset_path "./dataset/RoadScene/eval" --input_text "This is the infrared and visible light image fusion task."  --save_path "./results"

#### error
assert imgF.shape == imgA.shape == imgB.shape, 'shape error, F.shape:{}, A.shape:{}, B.shape:{}'.format(imgF.shape, imgA.shape, imgB.shape)
AssertionError: shape error, F.shape:(320, 432), A.shape:(320, 440), B.shape:(320, 440)

assert imgF.shape == imgA.shape == imgB.shape, 'shape error, F.shape:{}, A.shape:{}, B.shape:{}'.format(imgF.shape, imgA.shape, imgB.shape)
AssertionError: shape error, F.shape:(320, 576), A.shape:(331, 585), B.shape:(331, 585)

assert imgF.shape == imgA.shape == imgB.shape, 'shape error, F.shape:{}, A.shape:{}, B.shape:{}'.format(imgF.shape, imgA.shape, imgB.shape)
AssertionError: shape error, F.shape:(288, 496), A.shape:(299, 511), B.shape:(299, 511)

**Comment by XunpengYi** [comment]
非常感谢您的提问。这是因为，为了确保上采样和下采样能够满足网络要求，我们在数据处理时做了尺寸修改。您可以将分辨率后处理调整回原始尺寸。

**Comment by XunpengYi** [comment]
我们将在近期版本中更新，以减少后处理的繁琐。

**Comment by 123dzj** [comment]
> 非常感谢您的提问。这是因为，为了确保上采样和下采样能够满足网络要求，我们在数据处理时做了尺寸修改。您可以将分辨率后处理调整回原始尺寸。

你好，怎么进行后处理保证输入和输出一致大小呀
