### ISSUE TITLE
train_simple.py

### ISSUE THREAD

**Issue by JAWILU** [XunpengYi/Text-IF#16]
您好请问您的这个代码运行是不是有点问题？？目前看怎么没有这个文件了？请问会再公布可运行的该代码吗？

**Comment by XunpengYi** [comment]
您好，我们没有发布过train_simple.py的代码，如果您需要训练请运行train_fusion.py

**Comment by JAWILU** [comment]
哦哦，我看到您提供的simple_dataset.py，想着应该有个train_simple.py ，看来我弄错了。。

**Comment by XunpengYi** [comment]
如果觉得仓库、数据或者代码对您的研究有用的话，可以star一下~
