### ISSUE TITLE
一些问题

### ISSUE THREAD

**Issue by Danee-wawawa** [XunpengYi/Text-IF#7]
您好，
非常感谢您的工作，基于您的算法我有一些想尝试的，不知道是否可以，望您指导下~
我目前在做的是可见光图像生成红外图像，想问下您的算法是否也可以用于这个任务呢？比如输入是一张红外图，一张可见光图（两者非配对），然后文本提示为“这是一个可见光图像转换为红外图像的任务。”
从您对当前算法的熟悉度来看，上述我想要做的是否会有效果呢？
感谢指导，期待您的回复~

**Comment by XunpengYi** [comment]
如果您需要将融合任务转化为生成任务，可能需要根据任务先验重新训练网络。此外，文本提示更适合多任务的情况，例如存在可见光生成红外图像，也存在红外生成可见光图像等多种任务的情况下。
对于您的研究，将文本提示和扩散模型等生成模型结合将会是更有益的。

祝好~

**Comment by Danee-wawawa** [comment]
好咧，感谢回复~
关于“文本提示和扩散模型等生成模型结合”的方向我有看到一些论文和尝试，但是目前效果都不太好，请问下您有推荐的算法可以让我去尝试下吗？感谢~
祝好~

**Comment by XunpengYi** [comment]
您研究的领域我不是特别了解，就自然图像来说，stable diffusion提供的大模型还可以。

**Comment by Danee-wawawa** [comment]
好咧，感谢回复~^_^
